### PR TITLE
(RE-9648) Migrate vanagon projects to use buildsources in Artifactory

### PR DESCRIPTION
**Pull request by mwaggett**
This commit adds `artifactory_url` and `buildsources_url` settings and replaces buildsources.delivery.puppetlabs.net with Artifactory.

### CODE REVIEW

**Comment by mwaggett** [comment]
Failures seem to be because there isn't a C compiler in the $PATH on certain platforms:
http://jenkins-release.delivery.puppetlabs.net/job/vanagon_generic_job/1239/

**Comment by underscorgan** [comment]
@McdonaldSeanp @ScottGarman are those failures expected for pl-tar?

**Comment by ScottGarman** [comment]
The changes look safe, and I'll file a separate ticket to fix the solaris and windows builds for pl-tar. :+1:

**Comment by ScottGarman** [comment]
Note: I've filed PA-1696 for fixing the solaris/windows builds of pl-tar.

**Pull request merged**
