### PR TITLE
(maint) Refactor code and add the pl-gcc12 project.

### PR DESCRIPTION
**Pull request by isaac-hammes**

### CODE REVIEW

**Review by e-gris — CHANGES_REQUESTED** [review]
For pl-gcc12, I think we need to leave components/gcc.rb and projects/pl-gcc.rb alone and create a components/gcc12.rb.

**Review by e-gris — APPROVED** [review]

**Comment by e-gris** [comment]
LGTM! I have some minor style nitpicks (mostly in the stuff that I wrote) that I would prefer to add in a PR later after this has been merged & tested out.

**Comment by isaac-hammes** [comment]
@e-gris Would you like me to exclude all of the changes outside of pl-gcc12/gcc12?

**Comment by e-gris** [comment]
I think keeping the documentation changes would be a good idea but wholly optional.

However, pl-gcc itself (not pl-gcc12) should remain undisturbed and everything else should be purely additive.

**Comment by e-gris** [comment]
Also the auxiliary components (gmp, mpc, etc.)  likely need their md5sum moved to the project, like the versions are.

**Pull request merged**
