### PR TITLE
(PA-1498) Apply boost::filesystem::unique_path patch for Solaris-10

### PR DESCRIPTION
**Pull request by ekinanp**

### CODE REVIEW

**Comment by MikaelSmith** [comment]
I've tested that this fixes PCP-790, which failed because `unique_path` was throwing an exception on Solaris. As far as I can tell, downloading files for pxp-agent is the first place we've used unique_path outside of unit tests, so the impact of this should be limited.

**Comment by MikaelSmith** [comment]
We might need to bump the release number in config/projects/pl-boost.rb.

**Comment by ScottGarman** [comment]
If this doesn't impact Solaris 11, let's confine the change to Sol10 only. And yes, the release number in the projects/pl-boost.rb file will need to be updated (again, confined only to the affected platform(s))

**Comment by MikaelSmith** [comment]
I actually don't know if it impacts Solaris 11. I guess I'll give it a try.

**Comment by MikaelSmith** [comment]
Ok this does appear to only be a problem on Solaris 10. So I'm comfortable confining the patch to that and only rebuilding Solaris 10. We can get that into puppet-agent with minimal hassle.

@ekinanp Example of confining to Solaris 10: https://github.com/puppetlabs/puppet-agent/blob/master/configs/components/leatherman.rb#L10

**Comment by ScottGarman** [comment]
I'll backtrack on what I said about confining the release bump to solaris10 - you can make it global and it's not a big deal.

**Comment by MikaelSmith** [comment]
@ekinanp can you also file a PA ticket around this? I think I'll use the same to pick up the fixed build in puppet-agent (working on a PR for that).

**Comment by ScottGarman** [comment]
:+1:

**Comment by McdonaldSeanp** [comment]
Looks like some type changes in the patch, so 👍

**Pull request merged**
