### PR TITLE
Provide vanogon build tools for CentOS7 or RHELSA on AArch64

### PR DESCRIPTION
**Pull request by rhenwood-arm**
This patch assumes that the tools will be cross compiled on x86.

Signed-off-by: Richard Henwood richard.henwood@arm.com

### CODE REVIEW

**Comment by rhenwood-arm** [comment]
I have been in contact with @ahpook from the puppet team. I anticipate there could be a wrinkle or two with this patch against the specifics of the puppet internal build system. I am looking forward to your feedback so I can iron those out.

**Comment by ScottGarman** [comment]
Yeah, great work here @rhenwood-arm! Can you post a url to the sysroot tarball, and we'd be willing to run some test builds of it to verify it.

Also, can you verify on your host aarch64 system that:

gcc -dumpmachine

returns "aarch64-linux-gnu" and that your installed gcc rpm package has an arch of "aarch64"? I assume this is the case, but if there are any differences, it could cause issues later on during the agent package build.

**Comment by rhenwood-arm** [comment]
Thanks for the prompt and helpful feedback!

@ScottGarman : I didn't know about the 'dumpmachine' flag to gcc. It reveals that I should have used 'aarch64-redhat-linux' for CentOS/RHELSA. I will send a new PR, post-haste.

@stahnma (and Scott). I can figure out a way to share the sysroot from CentOS I have built on AArch64. Would that be useful?

Let me look into the RHELSA sysroot sharing (once I've fixed the machine triple).

**Comment by rhenwood-arm** [comment]
Oops. it looks like I've broken the typical PR workflow as well. I'll make a new pull request - sorry for the confusion.

**Pull request closed without merging**
